imported school list from databaseand made an html string of the list…
NSS-Day-Cohort-66/the-citadel-of-farolyn-buttery-butts pull request #11
Opened 2023-08-02 14:45 UTC by Jbartow92

…s of schools

2023-08-02 14:54 UTC, apittman7104 approved these changes

2023-08-02 15:05 UTC, Valerie-Freeman requested changes

2023-08-02 15:05 UTC, Valerie-Freeman commented on scripts/database.js
Please revert these changes. This functionality is being handled in another ticked.

2023-08-03 16:12 UTC, dontcallmeplath approved these changes

2023-08-03 16:23 UTC, seatonct approved these changes

2023-08-03 16:25 UTC, Valerie-Freeman approved these changes

2023-08-03 16:25 UTC, merged